name: tests

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true


jobs: # Docs: <https://help.github.com/en/articles/workflow-syntax-for-github-actions>
  git-leaks:
    name: GitLeaks
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
        with: {fetch-depth: 0, version: 8.16.0}

      - name: Check for GitLeaks
        with: {version: 8.16.0}
        uses: gacts/gitleaks@v1.2.0 # Action page: <https://github.com/gacts/gitleaks>
