name: tests

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true


jobs: # Docs: <https://help.github.com/en/articles/workflow-syntax-for-github-actions>
  git-leaks:
    name: GitLeaks
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
        with: {fetch-depth: 0, version: 8.16.0}

      - name: Check for GitLeaks
        with: {version: 8.16.0}
        uses: gacts/gitleaks@v1.2.0 # Action page: <https://github.com/gacts/gitleaks>

  check-style:
    name: Run check style (PHP cs fixer)
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.setup }}-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer update -n --prefer-dist --no-progress --ansi && composer info

      - name: Run php-cs-fixer
        run: composer check-style

  php-unit:
    name: Run check PHP Unit tests
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.setup }}-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer update -n --prefer-dist --no-progress --ansi && composer info

      - name: Run tests
        run: composer unit-test
